language: python
python:
  - "2.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE=cheddar.settings.tests
    - PYTHONPATH=src

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpq-dev

install:
  - pip install -r src/requirements.txt

script:
  - python src/manage.py test
