language: python
python:
  - "2.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE=cheddar.settings.tests
    - PYTHONPATH=src

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpq-dev

install:
  - pip install -r src/requirements.txt

script:
  - cd src/
  - coverage run manage.py test
  - coverage report --include=feeds*,cheddar*,accounts* -m --omit=*migrations*,*unittests*
  - flake8 accounts/
